### PR TITLE
Updating NuGet packages, target SDK and framework targets.

### PR DESCRIPTION
**Pull request by stebet**
* Updated global.json to target the latest 3.1 SDK.
* Updated NuGet references (no more preview packages!).
* Changed obsolete Attributes in the Banchmark project and changed targets to netcoreapp3.1 and net48 as benchmark jobs.

### CODE REVIEW

**Comment by mgravell** [comment]
fixing the `Microsoft.Bcl.AsyncInterfaces` and other lib dependencies - yup, makes perfect sense

re the SDK file; unless we need specific SDK features, it may be preferable to be more flexible; [example for consideration](https://github.com/protobuf-net/protobuf-net/blob/master/global.json) - this is far less picky

however, I'm a little less certain about the change from `netcoreapp3.0` to `netcoreapp3.1`; is there an actual reason for this? `netcoreapp3.1` can still consume the `netcoreapp3.0` TFM, so this reduces TFM coverage without (as far as I can tell) any other purpose; is that intentional?

**Comment by stebet** [comment]
SDK file: makes sense, I will update it.
TFM: No, think I just went a bit overboard with updating, will revert that back to netcoreapp3.0, doesn't make sense to update that to 3.1.

**Comment by stebet** [comment]
Updated, I kept the tests and benchmark as targets to 3.1 and .NET Framework 4.8, but that could of course be rolled back as well, although that does check the consumption of the netcoreapp3.0 TFM in a netcoreapp3.1 project, so maybe that makes sense?

**Comment by mgravell** [comment]
tests and benchmark update is fine

**Comment by mgravell** [comment]
looks good, thanks

**Pull request merged**
